apiVersion: v1
kind: Service
metadata: 
     name: flask-app
spec:
   selector: 
       name: flask-app
   ports: 
      - protocol: TCP
        port: 30017
        targetPort: 30017
type: LoadBalancer
